import type { Metadata } from "next";
import { headers } from "next/headers";

import "./globals.css";

import Header from "@/components/desktop/layout/header/Header";
import Navbar from "@/components/desktop/layout/navbar/Navbar";
import HeaderMob from "@/components/mobile/layout/header-mob/HeaderMob";
import Footer from "@/components/desktop/layout/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersList = headers();
  const userAgent = (await headersList).get("user-agent");

  let isMobileView = userAgent!.match(
    /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
  );

  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <div id="backdrop-root"></div>
        <div id="overlay-root"></div>
        {isMobileView ? (
          <HeaderMob />
        ) : (
          <>
            <Header />
            <Navbar />
          </>
        )}

        {children}
        {isMobileView ? <Footer isMob /> : <Footer />}
      </body>
    </html>
  );
}
