import kashmirOne from "@/images/kashmir-one.png";
import kashmirTwo from "@/images/kashmir-two.png";
import kashmirThree from "@/images/kashmir-three.png";
import kashmirFour from "@/images/kashmir-four.png";

export const packagesData = [
  {
    image: kashmirOne,
    title: "Kashmir Escape",
    duration: "3Days/2Nights",
    reviewCount: "50",
    stars: "4",
    datesFillingFast: [
      { date: "24 April, 25", seats: "(4 seats)" },
      { date: "06May, 25", seats: "(3 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹40,000",
    emi: "₹1,345",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirTwo,
    title: "Best of Kashmir",
    duration: "4Days/3Nights",
    reviewCount: "40",
    stars: "5",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "2 Cities" },
    cost: "₹50,000",
    emi: "₹2,345",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirThree,
    title: "Women's Special Kashmir",
    duration: "5Days/4Nights",
    reviewCount: "30",
    stars: "3",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "4 Cities" },
    cost: "₹60,000",
    emi: "₹345",
    tourType: ["Group", "Women Special"],
  },
  {
    image: kashmirFour,
    title: "Kashmir Escape",
    duration: "1Day",
    reviewCount: "10",
    stars: "2",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹10,000",
    emi: "₹145",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirOne,
    title: "Kashmir Escape",
    duration: "3Days/2Nights",
    reviewCount: "50",
    stars: "4",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "2 Dates", cities: "3 Cities" },
    cost: "₹40,000",
    emi: "₹1,345",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirTwo,
    title: "Best of Kashmir",
    duration: "4Days/3Nights",
    reviewCount: "40",
    stars: "5",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "5 Cities" },
    cost: "₹50,000",
    emi: "₹2,345",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirThree,
    title: "Women's Special Kashmir",
    duration: "5Days/4Nights",
    reviewCount: "30",
    stars: "3",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹60,000",
    emi: "₹345",
    tourType: ["Group", "Women Special"],
  },
  {
    image: kashmirFour,
    title: "Kashmir Escape",
    duration: "1Day",
    reviewCount: "10",
    stars: "2",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹10,000",
    emi: "₹145",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirOne,
    title: "Kashmir Escape",
    duration: "3Days/2Nights",
    reviewCount: "50",
    stars: "4",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹40,000",
    emi: "₹1,345",
    tourType: ["Group", "Family"],
  },
  {
    image: kashmirTwo,
    title: "Best of Kashmir",
    duration: "4Days/3Nights",
    reviewCount: "40",
    stars: "5",
    datesFillingFast: [
      { date: "24 August, 25", seats: "(8 seats)" },
      { date: "06June, 25", seats: "(2 seats)" },
    ],
    departures: { dates: "4 Dates", cities: "3 Cities" },
    cost: "₹50,000",
    emi: "₹2,345",
    tourType: ["Group", "Family"],
  },
];
